'use client';
import {useEffect,useState} from 'react';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Checkbox} from './ui/checkbox';
import {loadTake,updateTake,deleteTake,type TakeSummary} from '@/lib/take-store';
import {saveFile} from '@/lib/save-file';
export function Library({takes,onOpen,onRefresh}:{takes:TakeSummary[];onOpen:(id:string)=>void;onRefresh:()=>Promise<void>}){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState<string[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const visible=takes.filter(t=>t.name.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||(t.kind||'original')===filter));
 async function download(id:string){const t=takes.find(t=>t.id===id);if(!t)return;setBusy(true);setMessage('Choose where to save…');try{setMessage(await saveFile(async()=>{setMessage('Preparing file…');const saved=await loadTake(id);if(!saved)throw Error('This take is no longer in Library.');return saved.blob},t.name,t.mimeType))}catch(e){setMessage('Save failed: '+String(e))}finally{setBusy(false)}}
 async function copy(id:string){try{const t=await loadTake(id);if(!t)return;await navigator.clipboard.write([new ClipboardItem({'image/png':t.blob})]);setMessage('Image copied — paste into UltraMock')}catch(e){setMessage(String(e))}}
 async function remove(){if(!selected.length||!confirm(`Delete ${selected.length} local item(s)? Downloaded copies remain.`))return;setBusy(true);try{for(const id of selected)await deleteTake(id);setSelected([]);await onRefresh()}catch(e){setMessage(String(e))}finally{setBusy(false)}}
 return <section className="media-library"><div className="library-heading"><div><h1>Your library</h1><p>Original captures, screenshots, and finished exports. Stored in this browser.</p></div><span>{takes.length} items</span></div><div className="library-tools"><Input aria-label="Search library" placeholder="Search captures…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter library" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All media</option><option value="original">Originals</option><option value="screenshot">Screenshots</option><option value="export">Exports</option></select><Button onClick={()=>setSelected(selected.length?[]:visible.map(t=>t.id))}>{selected.length?'Clear selection':'Select all'}</Button><Button disabled={!selected.length||busy} onClick={remove}>Delete {selected.length||''}</Button></div>{message&&<p role="status">{message}</p>}<div className="library-grid">{visible.map(t=><article className={`media-card ${selected.includes(t.id)?'selected':''}`} key={t.id}><div className="media-selection"><Checkbox aria-label={`Select ${t.name}`} checked={selected.includes(t.id)} onCheckedChange={v=>setSelected(s=>v?[...s,t.id]:s.filter(id=>id!==t.id))}/><span>{t.kind||'original'}</span></div><Thumbnail take={t} onOpen={()=>onOpen(t.id)}/><h2 title={t.name}>{t.name}</h2><p>{t.width?`${t.width} × ${t.height} · `:''}{t.duration?`${t.duration.toFixed(1)}s · `:''}{(t.bytes/1048576).toFixed(1)} MB</p><p>{new Date(t.createdAt).toLocaleString()}</p><div className="media-actions"><Button onClick={()=>onOpen(t.id)}>{t.mimeType.startsWith('image/')?'View':'Edit'}</Button><Button onClick={()=>download(t.id)}>Save</Button>{t.mimeType==='image/png'&&<Button onClick={()=>copy(t.id)}>Copy image</Button>}<Button onClick={async()=>{const name=prompt('Name this capture',t.name)?.trim();if(name)try{await updateTake(t.id,{name});await onRefresh()}catch(e){setMessage(String(e))}}}>Rename</Button></div></article>)}</div>{!visible.length&&<div className="library-empty"><h2>{takes.length?'No matching captures':'Your next take starts here'}</h2><p>Record your phone or import a video. Originals stay separate from edits.</p></div>}</section>
}
function Thumbnail({take,onOpen}:{take:TakeSummary;onOpen:()=>void}){
 const [src,setSrc]=useState(take.thumbnail||'');
 useEffect(()=>{let cancelled=false,url='';if(take.thumbnail){setSrc(take.thumbnail);return}void loadTake(take.id).then(t=>{if(!t||cancelled)return;url=URL.createObjectURL(t.blob);if(t.mimeType.startsWith('image/')){setSrc(url);return}const v=document.createElement('video');v.preload='metadata';v.muted=true;v.src=url;v.onloadeddata=()=>{if(cancelled)return;const c=document.createElement('canvas');c.width=160;c.height=Math.round(v.videoHeight/v.videoWidth*160);c.getContext('2d')!.drawImage(v,0,0,c.width,c.height);const thumbnail=c.toDataURL('image/jpeg',.65);setSrc(thumbnail);void updateTake(t.id,{thumbnail,width:v.videoWidth,height:v.videoHeight,...(Number.isFinite(v.duration)?{duration:v.duration}:{})}).catch(()=>{})}}).catch(()=>{});return()=>{cancelled=true;if(url)URL.revokeObjectURL(url)}},[take.id,take.thumbnail]);
 return <button className="media-thumbnail" aria-label={`Open ${take.name}`} onClick={onOpen}>{src?<img src={src} alt=""/>:<span>Video</span>}</button>
}
